Hotfix migrate is admin
bloomingseed/sos-connect-auth pull request #4
Opened 2021-11-02 19:46 UTC by bloomingseed

2021-11-05 07:40 UTC, nvcgooner requested changes

2021-11-05 07:40 UTC, nvcgooner commented on routers/Accounts.js
> +    date_created: new Date(),
missed is_admin=true

2021-11-07 09:37 UTC, bloomingseed commented
@nvcgooner

2021-11-07 10:53 UTC, nvcgooner approved these changes

2021-11-07 12:56 UTC, merged